### ISSUE TITLE
pci flags 0xc3080 error

### ISSUE THREAD

**Issue by notluke27** [lshbluesky/Samsung-NT750XDA-KF59U-Hackintosh#10]
![20230827_160234](https://github.com/lshbluesky/Samsung-NT750XDA-KF59U-Hackintosh/assets/77593871/14ca097f-90c3-4e95-af00-76c32700972b)
I can't get past this pci error
laptop model: galaxy book2 - 550XED with 12th gen core i5
OS version: tried catalina, monterey and ventura

**Comment by lshbluesky** [comment]
You should resolve the `ACPI Error` above, not the `pci flags 0xc3080` log.
The `pci flags 0xc3080` log is a normal output log and is not an error.
It just stopped booting and the last log was the `pci flags 0xc3080` log.

Make sure the SSDT you are using is compatible with your laptop's ACPI path.
Also, try booting using only the essential SSDT.

**Comment by notluke27** [comment]
which SSDTs are essential for booting? I made these with SSDTTime and i will try to boot with them now
![image](https://github.com/lshbluesky/Samsung-NT750XDA-KF59U-Hackintosh/assets/77593871/5a789848-7ab3-47a5-bac7-58692ea0a053)

**Comment by notluke27** [comment]
![IMG_20230901_170039](https://github.com/lshbluesky/Samsung-NT750XDA-KF59U-Hackintosh/assets/77593871/0d24d1a7-5d8b-41ef-b1c0-2a06130ff5ac)
It's giving me a x86_validate_topology error now

**Comment by lshbluesky** [comment]
> ![IMG_20230901_170039](https://user-images.githubusercontent.com/77593871/265116882-0d24d1a7-5d8b-41ef-b1c0-2a06130ff5ac.jpg) It's giving me a x86_validate_topology error now

Set ProvideCurrentCpuInfo to True in Kernel - Quirks in Config.plist.
Additionally, you may need to use SSDT-PLUG-ALT.aml.

**Comment by notluke27** [comment]
now i'm stuck on Err(0xE), 0 @ LocHB 71B4903C the same place i got stuck when i created my own EFI

**Comment by lshbluesky** [comment]
> now i'm stuck on Err(0xE), 0 @ LocHB 71B4903C the same place i got stuck when i created my own EFI

Try changing ProvideCurrentCpuInfo back to Flase in Kernel - Quirks in Config.plist.

**Comment by notluke27** [comment]
there is not such option on the BIOS

**Comment by lshbluesky** [comment]
> there is not such option on the BIOS

Sorry, but I'm not sure anymore.
