### ISSUE TITLE
hello, thanks for your work and research, i also managed to boot my tigerlake laptop, mine is i5-11320h and also have the same iris xe igpu. im not that good at hackintosh, is there any progress in the qe/ci? maybe i could help or testing something

### ISSUE THREAD

**Issue by thisisharshavardhan** [lshbluesky/Samsung-NT750XDA-KF59U-Hackintosh#21]
Can you send me the EFI folder to thisisharshavardhan@gmail.com

**Comment by lshbluesky** [comment]
1. QE/CI graphics acceleration has not been activated yet.
2. If you would like assistance or testing, please refer to the [InsanelyMac forum.](https://www.insanelymac.com/forum/topic/358305-80-solved-iris-xe-igpu-on-tiger-lake-successfully-loaded-icllp-frambuffer-and-vram-also-recognizes-1536mb-however-some-issues/)
3. For the EFI folder, use the EFI folder in this repo.
