### ISSUE TITLE
Used EFI as base on 11400H, got to boot with no trackpad working

### ISSUE THREAD

**Issue by NotLugozzi** [lshbluesky/Samsung-NT750XDA-KF59U-Hackintosh#22]
Good afternoon, i stumbled across your efi and wanted to take a quick peek for getting my laptop to work too (Asus FX506HC). I remade all ACPI files, changed some KEXTS and remade part of the config.plist. i can boot and i can also get to recovery, but trackpad is refusing to work.

Specs:

CPU: Intel 11th Gen Tiger Lake Core i7-11400H@ 2.7GHz
GPU: Intel Iris XE Graphics G7
RAM: 2x8 DDR4 @ 3600 MHz
STORAGE: 1x Intel SSDPEKNW512G8H 500gb nvme drive; 1x WD Blue SN570 500gb nvme
MOTHERBOARD: HN057W
WIFI/BT: Intel Wi-Fi 6 AX201 160MHz
AUDIO CODEC: Realtek HD Audio ALC256
ETHERNET: Realtek RTL8111
I2C: Asus Precision Touchpad (Elan1203)

**Comment by lshbluesky** [comment]
Since your laptop has an Intel 11th Gen Tiger Lake Core i7-11400H CPU, the chipset is Tiger Lake-H, not Tiger Lake-LP.
Therefore, you must add the Device ID of your laptop's I2C Controller to Info.plist in VoodooI2C.
You can check the Device ID of the I2C Controller in the PCI device information of the Hackintool app.

Open the `Info.plist` of `VoodooI2C.kext` and add the PCI ID below under `VoodooI2CPCILakeController`.

**Comment by NotLugozzi** [comment]
oh i see, what if i can't get to mac desktop yet to check the device id? can i retrieve it from windows or linux?

**Comment by lshbluesky** [comment]
> oh i see, what if i can't get to mac desktop yet to check the device id? can i retrieve it from windows or linux?

You can check the Device ID of `Intel Serial IO I2C Host Controller` in Device Manager.

But, regardless of the detailed model name of the CPU, if it is a `Tiger Lake-H` chipset, it will be `0x43e88086`.
https://devicehunt.com/view/type/pci/vendor/8086/device/43E8

Therefore, just add the PCI ID below.
`0x43e88086&amp;0xFFFCFFFF`

**Comment by NotLugozzi** [comment]
tried adding the PCI id and it still refuses to work. this is my [efi](https://git.mercurio.moe/Mercury/Asus-FX506HC-HN057W-opencore) if you wanna take a quick peek at it

**Comment by lshbluesky** [comment]
> tried adding the PCI id and it still refuses to work. this is my [efi](https://git.mercurio.moe/Mercury/Asus-FX506HC-HN057W-opencore) if you wanna take a quick peek at it

The I2C TouchPad does not work simply by adding VoodooI2C.kext and requires an ACPI patch.
Have you patched the `_CRS Method` of the device corresponding to the I2C TouchPad to operate in Interrupt (GPIO) mode?

Additionally, in the case of ASUS laptops, Interrupt (GPIO) mode may not work well, and in this case, it is recommended to use Polling mode.
Try adding `-vi2c-force-polling` boot arg.

**Comment by NotLugozzi** [comment]
i haven't checked the _crs patch yet and I have also not tried vi2c polling. I'll give it a go as soon as I get back to my PC.
thanks again for the help you're giving me :)
